include:
  - board: ble_micro_pro
    shield: torabo_tsuki_left
    snippet: studio-rpc-usb-uart
    artifact-name: torabo_tsuki_left_peripheral
  - board: ble_micro_pro
    shield: torabo_tsuki_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
    artifact-name: torabo_tsuki_right_central
